name: Create Indexes
description: 'create-index'
inputs:
  source:
    description: 'The source of the executable'
    required: false
    default: https://exponential-workload.github.io/create-index-bin/out/index-${{runner.os == 'Linux' && 'linux' || runner.os == 'Windows' && 'win.exe' || 'macos'}}
  path:
    description: 'The path to the executable'
    required: false
    default: ${{runner.os=='Windows'&&'C:'||''}}/create-index-${{runner.os == 'Linux' && 'linux' || runner.os == 'Windows' && 'win.exe' || 'macos'}}
  shell:
    description: 'The shell to use'
    required: false
    default: ${{runner.os == 'Linux' && 'bash' || runner.os == 'Windows' && 'cmd.exe' || 'sh'}}
runs:
  using: "composite"
  steps:
    - name: Download Executable
      run: ${{runner.os=='Windows' && '' || 'sudo '}}curl -o "${{ inputs.path }}" "${{ inputs.source }}"
      if: runner.os != 'macOS'
      shell: ${{ inputs.shell }}
    - name: Change Permissions
      if: runner.os != 'Windows' && runner.os != 'macOS'
      run: |
        sudo chmod 777 "${{ inputs.path }}"
      shell: ${{ inputs.shell }}
    - name: Run Executable
      if: runner.os != 'macOS'
      run: |
        "${{ inputs.path }}"
      shell: ${{ inputs.shell }}
    - name: Run action under MacOS
      if: runner.os == 'macOS'
      run: |
        sudo curl -o "${{ inputs.path }}" "${{ inputs.source }}"
        sudo chmod 777 "${{ inputs.path }}"
        "${{ inputs.path }}"
      shell: zsh