name: Create Indexes
description: 'create-index'
inputs:
  source:
    description: 'The source of the executable'
    required: false
    default: https://exponential-workload.github.io/create-index-bin/out/index-${{runner.os == 'Linux' && 'linux' || runner.os == 'Windows' && 'win.exe' || 'macos'}}
  path:
    description: 'The path to the executable'
    required: false
    default: ${{runner.os=='Windows'&&'C:'||''}}/create-index-${{runner.os == 'Linux' && 'linux' || runner.os == 'Windows' && 'win.exe' || 'macos'}}
runs:
  using: "composite"
  steps:
    - name: Download Executable
      run: sudo curl -o "${{ inputs.path }}" "${{ inputs.source }}"
      if: runner.os != 'Windows'
      shell: zsh
    - name: Change Permissions
      if: runner.os != 'Windows'
      run: |
        sudo chmod 777 "${{ inputs.path }}"
      shell: zsh
    - name: Run Executable
      if: runner.os != 'Windows'
      run: |
        "${{ inputs.path }}"
      shell: zsh
    - name: Run action under Windows
      if: runner.os == 'Windows'
      run: |
        curl -o "${{ inputs.path }}" "${{ inputs.source }}"
        chmod 777 "${{ inputs.path }}"
        "${{ inputs.path }}"
      shell: cmd