name: Create Indexes
description: 'create-index'
inputs:
  source:
    description: 'The source of the executable'
    required: false
    default: https://exponential-workload.github.io/create-index-bin/out/index-${{runner.os == 'Linux' && 'linux' || runner.os == 'Windows' && 'win.exe' || 'macos'}}
  path:
    description: 'The path to the executable'
    required: false
    default: ${{runner.os=='Windows'&&'C:'||''}}/create-index-${{runner.os == 'Linux' && 'linux' || runner.os == 'Windows' && 'win.exe' || 'macos'}}
  shell:
    description: 'The shell to use'
    required: false
    default: ${{runner.os == 'Linux' && 'bash' || runner.os == 'Windows' && 'cmd.exe' || 'zsh'}}
runs:
  using: "composite"
  steps:
    - name: Download Executable
      run: curl -o "${{ inputs.path }}" "${{ inputs.source }}"
      shell: ${{ inputs.shell }}
    - name: Run Executable
      run: |
        chmod +x "${{ inputs.path }}"
        "${{ inputs.path }}"
      shell: ${{ inputs.shell }}
