name: Create Indexes
description: 'create-index'
icon: 'align-center'
color: 'purple'
inputs:
  source:
    description: 'The source of the executable'
    required: false
    default: https://exponential-workload.github.io/create-index-bin/out/index-${{runner.os == 'Linux' && 'linux' || runner.os == 'Windows' && 'win.exe' || 'macos'}}
  path:
    description: 'The path to the executable'
    required: false
    default: ${{runner.os=='Windows'&&'C:'||runner.os=='macOS'&&'/Users/runner/work'||'/home/runner/work'}}/create-index-${{runner.os == 'Linux' && 'linux' || runner.os == 'Windows' && 'win.exe' || 'macos'}}
  dir:
    description: 'Directory to index'
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Download Executable
      run: curl -o "${{ inputs.path }}" "${{ inputs.source }}"
      if: runner.os != 'Windows'
      shell: bash
    - name: Change Permissions
      if: runner.os != 'Windows'
      run: |
        chmod 777 "${{ inputs.path }}"
      shell: bash
    - name: Run Executable
      if: runner.os != 'Windows'
      run: |
        "${{ inputs.path }}" build "${{inputs.dir}}"
      shell: bash
    - name: Run action under Windows
      if: runner.os == 'Windows'
      run: |
        curl -o "${{ inputs.path }}" "${{ inputs.source }}"
        chmod 777 "${{ inputs.path }}"
        "${{ inputs.path }}" build "${{inputs.dir}}"
      shell: cmd